document.write( '<footer id=\"footer-home\">\n' );
document.write( '<div class=\"footer-content\">\n' );
document.write( '<div class=\"container\">\n' );
document.write( '<div class=\"row gap-y\">\n' );
document.write( '<div class=\"col-lg-4col-lg-2 col-md-4\">\n' );
document.write( '<!-- Footer widget area 1 -->\n' );
document.write( '<div class=\"widgetwidget-contact-us\" style=\"background-image: url(\'images/world-map-dark.png\'); background-position: 50% 20px; background-repeat: no-repeat\">\n' );
document.write( '<h4>About EPICODE</h4>\n' );
document.write( '<ul class=\"list-icon\">\n' );
document.write( '<li><i class=\"fa fa-file\"></i>CIN:&nbsp;&nbsp;&nbsp;U72900KA2020PTC131771</li>\n' );
document.write( '<li><i class=\"fa fa-map-marker-alt\"></i>Unit # 2201A, 22nd Floor, World Trade Centre, Rajajinagar, Bangalore - 560055</li>\n' );
document.write( '<li><i class=\"fa fa-phone\"></i>+9180-67935393</li>\n' );
document.write( '<li><i class=\"far fa-envelope\"></i> <a href=\"mailto:enquire@epicode.in\">enquire@epicode.in</a> </li>\n' );
document.write( '</ul>\n' );
document.write( '</div>\n' );
document.write( '<!-- end: Footer widget area 1 -->\n' );
document.write( ' </div>\n' );
document.write( '<div class=\"col-6 col-md-3 col-xl-2\">\n' );
document.write( '<!-- Footer widget area 1 -->\n' );
document.write( '<div class=\"widget\">\n' );
document.write( '<h4>PRODUCTS</h4>\n' );
document.write( '<ul class=\"list\">\n' );
document.write('<li><a href=\"products/epicode-irahive.html\">IraHive</a></li>\n');
document.write('<li><a href=\"products/epicode-robotasker.html\">Robotasker</a></li>\n');
document.write( '<li><a href=\"products/epicode-sahaya.html\">Sahaya Ticketing</a></li>\n' );
document.write( '<li><a href=\"products/epicode-cloud-telephony-enablers.html\">Cloud Telephony Enablers</a></li>\n' );
document.write( '</ul>\n' );
document.write( '</div>\n' );
document.write( '<!-- end: Footer widget area 1 -->\n' );
document.write( '</div>\n' );
document.write( '<div class=\"col-6 col-md-6 col-xl-2\">\n' );
document.write( '<!-- Footer widget area 3 -->\n' );
document.write( '<div class=\"widget\">\n' );
document.write( '<h4>COMPANY</h4>\n' );
document.write( '<ul class=\"list\">\n' );
document.write( '<li><a href=\"about-us.html\">About</a></li>\n' );
document.write( '<li><a href=\"contact-us.html\">Contact</a></li>\n' );
document.write('<li><a href=\"resources/blog.html\">Blog</a></li>\n');
document.write('<li><a href=\"resources/faq.html\">FAQ\'s</a></li>\n');
document.write( '</ul>\n' );
document.write( '</div>\n' );
document.write( '<!-- end: Footer widget area 3 -->\n' );
document.write( '</div>\n' );
document.write( '<div class=\"col-md-6 col-xl-4\">\n' );
document.write( '<p><a href=\"#\"><img src=\"images/epicode-logo-web.png\" style=\"width: 60%;\" alt=\"logo\"></a></p>\n' );
document.write( '<p>Technological Innovation is the cornerstone of our success mantra. </p>\n' );
document.write( '</div>\n' );
document.write( '</div>\n' );
document.write( '</div>\n' );
document.write( '</div>\n' );
document.write( '<div class=\"copyright-content\">\n' );
document.write( '<div class=\"container\">\n' );
document.write('<div class=\"copyright-text text-center\">© ');
document.write('<script>document.write(new Date().getFullYear())</script> Epicode Private Limited.All Rights Reserved. </div >\n');
document.write( '</div>\n' );
document.write( '</div>\n' );
document.write( '</footer>' );
