document.write( '<div class=\"body-inner\">\n' );
document.write( '\n' );
document.write( '<!-- Topbar -->\n' );
document.write( '<div id=\"topbar\" class=\"topbar-dark topbar-fullwidth dark d-none d-xl-block d-lg-block\">\n' );
document.write( '<div class=\"container\">\n' );
document.write( '<div class=\"row\">\n' );
document.write( '<div class=\"col-md-6\">\n' );
document.write( '<ul class=\"top-menu\">\n' );
document.write( '<li><a href=\"#\">Phone: +9180-67935393</a></li>\n' );
document.write( '<li><a href=\"mailto:enquire@epicode.in\">Email: enquire@epicode.in</a></li>\n' );
document.write( '</ul>\n' );
document.write( '</div>\n' );
document.write( '<div class=\"col-md-6 d-none d-sm-block\">\n' );
// document.write( '<div class=\"social-icons social-icons-colored-hover\">\n' );
// document.write( '<ul>\n' );
// document.write( '<li class=\"social-facebook\"><a href=\"#\" title=\"Coming soon\"><i class=\"fab fa-facebook-f\"></i></a></li>\n' );
// document.write( '<li class=\"social-twitter\"><a href=\"#\" title=\"Coming soon\"><i class=\"fab fa-twitter\"></i></a></li>\n' );
// document.write( '<li class=\"social-linkedin\"><a href=\"#\" title=\"Coming soon\"><i class=\"fab fa-linkedin\"></i></a></li>\n' );
// document.write( '<li class=\"social-youtube\"><a href=\"#\" title=\"Coming soon\"><i class=\"fab fa-youtube\"></i></a></li>\n' );
// document.write( '</ul>\n' );
// document.write( '</div>\n' );
document.write( '</div>\n' );
document.write( '</div>\n' );
document.write( '</div>\n' );
document.write( '</div>\n' );
document.write( '<!-- end: Topbar -->\n' );
document.write( '<!-- Header -->\n' );
document.write( '<header id=\"header\" data-transparent=\"true\" data-responsive-fixed=\"true\" class=\"dark submenu-light\">\n' );
document.write( '<div class=\"header-inner\">\n' );
document.write( '<div class=\"container\">\n' );
document.write( '<!--Logo-->\n' );
document.write( '<div id=\"logo\">\n' );
document.write( '<a href=\"index.html\">\n' );
document.write( '<span><img src=\"images/epicode-logo-web.png\" style=\"width:60%;\" /></span>\n' );
document.write( '</a>\n' );
document.write( '</div>\n' );
document.write( '<!--End: Logo-->\n' );
document.write( '<!--Navigation Resposnive Trigger-->\n' );
document.write( '<div id=\"mainMenu-trigger\">\n' );
document.write( '<a class=\"lines-button x\"><span class=\"lines\"></span></a>\n' );
document.write( '</div>\n' );
document.write( '<!--end: Navigation Resposnive Trigger-->\n' );
document.write( '<!--Navigation-->\n' );
document.write( '<div id=\"mainMenu\">\n' );
document.write( '<div class=\"container\">\n' );
document.write( '<nav>\n' );
document.write( '<ul>\n' );
document.write( '<li><a href=\"index.html\">Home</a></li>\n' );
document.write( '<li class=\"dropdown\"><a href=\"products.html\">Products</a>\n' );
document.write( '<ul class=\"dropdown-menu\">\n' );
document.write( '<li><a href=\"products/epicode-irahive.html\">IraHive</a></li>\n' );
document.write('<li><a href=\"products/epicode-robotasker.html\">Robotasker</a></li>\n');
document.write('<li><a href=\"products/epicode-sahaya.html\">Sahaya Ticketing</a></li>\n');
// document.write( '<li><a href=\"products/epicode-cloud-telephony-enablers.html\">Cloud Telephony Enablers</a></li>\n' );
document.write( '<li class=\"dropdown-submenu\"><a href=\"products/epicode-cloud-telephony-enablers.html\">Cloud Telephony Enablers</a>\n' );
document.write( '<ul class=\"dropdown-menu\">\n' );
document.write( '<li><a href=\"products/epicode-iracpa.html\">IraCPA</a></li>\n' );
document.write('<li><a href=\"products/epicode-iradialer.html\">IraDialer</a></li>\n');
document.write('<li><a href=\"products/epicode-irapda.html\">IraPDA</a></li>\n');
document.write('<li><a href=\"products/epicode-iraivrs.html\">IraIVRS</a></li>\n');
document.write('<li><a href=\"products/epicode-iratap.html\">IraTap</a></li>\n');
document.write('<li><a href=\"products/epicode-botcompose.html\">BotCompose</a></li>\n');

document.write( '</ul>\n' );
document.write( '</li>' );
document.write( '</ul>\n' );
document.write( '</li>\n' );
document.write( '<li class=\"dropdown\"><a href=\"solutions.html\">Solutions</a>\n' );
document.write( '<ul class=\"dropdown-menu\">\n' );
document.write('<li><a href=\"solutions/epicode-outbound-dialer.html\">Outbound Dialer for CRM </a></li>\n');
document.write('<li><a href=\"solutions/epicode-telephony-suite.html\">Telephony Suite for CRM</a></li>\n');
document.write('<li><a href=\"solutions/epicode-automated-invoice.html\">Automated Invoice Processing </a></li>\n');
document.write( '</ul>\n' );
document.write( '</li>\n' );
// document.write( '<li class=\"dropdown\"><a href=\"industries.html\">Industries</a>\n' );
// document.write( '<ul class=\"dropdown-menu\">\n' );
// document.write( '<li><a href=\"industries/epicode-bfsi.html\">BFSI</a></li>\n' );
// document.write( '<li><a href=\"industries/epicode-ecommerce.html\">Ecommerce</a></li>\n' );
// document.write( '<li><a href=\"industries/epicode-ed-tech.html\">Ed Tech</a></li>\n' );
// document.write( '<li><a href=\"industries/epicode-service-providers.html\">Service providers</a></li>\n' );
// document.write( '<li><a href=\"industries/epicode-enterprise.html\">Enterprise</a></li>\n' );
// document.write( '</ul>\n' );
// document.write( '</li>\n' );


//document.write('<li class=\"dropdown\"><a href=\"../services.html\">Services</a>\n');
//document.write('<ul class=\"dropdown-menu\">\n');
//document.write('<li><a href=\"../resources/blog.html\">Application Development using Epicode Stack</a></li>\n');
//document.write('</ul>\n');
//document.write('</li>');

document.write('<li class=\"dropdown\"><a href=\"downloads.html\">Resources</a>\n');
document.write('<ul class=\"dropdown-menu\">\n');
document.write('<li><a href=\"resources/blog.html\">BLOG</a></li>\n');
document.write('<li><a href=\"resources/faq.html\">FAQ\'s</a></li>\n');
document.write('</ul>\n');
document.write('</li>');
// document.write( '<li><a href=\"solutions/epicode-smart-self-service-ivrs.html\">Smart Self Service - IVRS</a></li>\n' );
// document.write( '<li><a href=\"solutions/epicode-iracpa.html\">IraCPA</a></li>\n' );
// document.write( '<li><a href=\"solutions/epicode-iradialer.html\">IraDialer</a></li>\n' );
document.write( '<li class=\"dropdown mega-menu-item\"><a href=\"about-us.html\">About Us</a></li>\n' );
document.write( '<li class=\"dropdown\"><a href=\"contact-us.html\">Contact Us</a></li>\n' );
/*document.write( '<li class=\"dropdown mega-menu-item\"><a href=\"faq.html\">FAQ\'s</a></li>\n' );
document.write( '<li class=\"dropdown mega-menu-item\"><a href=\"blog.html\">Blog</a></li>\n' );*/
document.write( '</ul>\n' );
document.write( '</nav>\n' );
document.write( '</div>\n' );
document.write( '</div>\n' );
document.write( '<!--end: Navigation-->\n' );
document.write( '</div>\n' );
document.write( '</div>\n' );
document.write( '</header>' );
